log4r_config:
#  pre_config:
#    global:
#      level: DEBUG
#    root:
#      level: DEBUG
  loggers:
    - name      : "wraith"
      level: DEBUG
      outputters :
        - console
    - name      : "donk"
      level: DEBUG
      outputters :
        - console

  outputters:
  - type: StdoutOutputter
    name: console
    formatter:
      pattern     : '%d %l: %m '
      type        : PatternFormatter
